version: "3.8"

x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_NAME: ${POSTGRES_NAME}

services:
  database:
    restart: always
    image: postgres:alpine
    environment:
      <<: *x-postgres-environment
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      basic:

  backend:
    build: backend
    environment:
      <<: *x-postgres-environment
      SECURITY_TOKEN: ${SECURITY_TOKEN}
    ports:
      - "8001:8000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./backend/app:/application"

    networks:
      basic:


volumes:
  pgdata:

networks:
  basic:
    driver: bridge

